platform :ios, '9.0'

target 'WReaderHostiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #需要添加的代码  flutter_module是自己创建的名字
  flutter_application_path = '../wreader_flutter_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)
# 依赖数据库
pod 'FMDB', '2.7.5'
pod 'WHToast','~>0.0.3'

end